export default function handler(req, res) {
  const data = [
    {
      key: 1,
      category: `FOOD`,
      title: `Eat low on the food chain`,
      content: `This means eating mostly fruits, veggies, grains, and beans. Livestock—meat and dairy—is responsible for 14.5 percent of manmade global greenhouse gas emissions, mainly from feed production and processing and the methane (25 times more potent than CO2 at trapping heat in the atmosphere over 100 years) that beef and sheep belch out. Every day that you forgo meat and dairy, you can reduce your carbon footprint by 8 pounds—that's 2,920 pounds a year. You can start by joining Meatless Mondays.`,
    },
    {
      key: 2,
      category: `FOOD`,
      title: `Choose organic and local `,
      content: `foods that are in season. Transporting food from far away, whether by truck, ship, rail or plane, uses fossil fuels for fuel and for cooling to keep foods in transit from spoiling.`,
    },
    {
      key: 3,
      category: `FOOD`,
      title: `Buy foodstuffs in bulk`,
      content: `Buy foodstuffs in bulk when possible using your own reusable container.`,
    },
    {
      key: 4,
      category: `FOOD`,
      title: `Reduce your food waste`,
      content: `Reduce your food waste by planning meals ahead of time, freezing the excess and reusing leftovers.`,
    },
    {
      key: 5,
      category: `FOOD`,
      title: `Compost `,
      content: `your food waste if possible. (If you live in New York City, you can find a`,
    },
    {
      key: 6,
      category: `CLOTHING`,
      title: `Don't buy fast fashion`,
      content: `Trendy, cheap items that go out of style quickly get dumped in landfills where they produce methane as they decompose. Currently, the average American discards about 80 pounds of clothing each year, 85 percent of which ends up in landfills. In addition, most fast fashion comes from China and Bangladesh, so shipping it to the U.S. requires the use of fossil fuels. Instead, buy quality clothing that will last.`,
    },
    {
      key: 7,
      category: `CLOTHING`,
      title: `buy vintage or recycled clothing`,
      content: `Even better, buy vintage or recycled clothing at consignment shops.`,
    },
    {
      key: 8,
      category: `CLOTHING`,
      title: `Wash your clothing in cold water`,
      content: `The enzymes in cold water detergent are designed to clean better in cold water. Doing two loads of laundry weekly in cold water instead of hot or warm water can save up to 500 pounds of carbon dioxide each year.`,
    },
    {
      key: 9,
      category: `CLOTHING`,
      title: `Buy less stuff!`,
      content: `Buy less stuff! And buy used or recycled items whenever possible.`,
    },
    {
      key: 10,
      category: `CLOTHING`,
      title: `reusable bag `,
      content: ` Bring your own reusable bag when you shop.`,
    },
    {
      key: 11,
      category: `CLOTHING`,
      title: `Excess packacge`,
      content: ` Try to avoid items with excess packaging.`,
    },
    {
      key: 12,
      category: `CLOTHING`,
      title: `laptop over desktop`,
      content: `If you're in the market for a new computer, opt for a laptop instead of a desktop. Laptops require less energy to charge and operate than desktops.`,
    },
    {
      key: 13,
      category: `CLOTHING`,
      title: `Energy Star products`,
      content: ` If shopping for appliances, lighting, office equipment or electronics, look for Energy Star products, which are certified to be more energy efficient.`,
    },
    {
      key: 14,
      category: `CLOTHING`,
      title: `Support eco friendly companies`,
      content: `Support and buy from companies that are environmentally responsible and sustainable.`,
    },
    {
      key: 15,
      category: `HOME`,
      title: `Energy auditing `,
      content: `Do an energy audit of your home. This will show how you use or waste energy and help identify ways to be more energy efficient.`,
    },
    {
      key: 16,
      category: `HOME`,
      title: `Change bulbs`,
      content: `Change incandescent light bulbs (which waste 90 percent of their energy as heat) to light emitting diodes (LEDs). Though LEDs cost more, they use a quarter of the energy and last up to 25 times longer. They are also preferable to compact fluorescent lamp (CFL) bulbs, which emit 80 percent of their energy as heat and contain mercury.`,
    },
    {
      key: 17,
      category: `HOME`,
      title: `Switch lights off `,
      content: `Switch lights off when you leave the room and unplug your electronic devices when they are not in use.`,
    },
    {
      key: 18,
      category: `HOME`,
      title: `Lower heater`,
      content: `Turn your water heater down to 120˚F. This can save about 550 pounds of CO2 a year.`,
    },
    {
      key: 19,
      category: `HOME`,
      title: ` low-flow showerhead `,
      content: `Installing a low-flow showerhead to reduce hot water use can save 350 pounds of CO2. Taking shorter showers helps, too.`,
    },
    {
      key: 20,
      category: `HOME`,
      title: `Lower thermostat`,
      content: `Lower your thermostat in winter and raise it in summer. Use less air conditioning in the summer; instead opt for fans, which require less electricity. And check out these other ways to beat the heat without air conditioning.`,
    },
    {
      key: 21,
      category: `HOME`,
      title: `Use clean energy`,
      content: `Sign up to get your electricity from clean energy through your local utility or a certified renewable energy provider. Green-e.org can help you find certified green energy providers.`,
    },
    {
      key: 22,
      category: `TRANSPORT`,
      title: `Drive less. `,
      content: `Walk, take public transportation, carpool, rideshare or bike to your destination when possible. This not only reduces CO2 emissions, it also lessens traffic congestion and the idling of engines that accompanies it.`,
    },
    {
      key: 23,
      category: `TRANSPORT`,
      title: `Avoid unnecessary braking and acceleration.`,
      content: `If you must drive, avoid unnecessary braking and acceleration. Some studies found that aggressive driving can result in 40 percent more fuel consumption than consistent, calm driving.`,
    },
    {
      key: 24,
      category: `TRANSPORT`,
      title: `Take care of your car`,
      content: ` Keeping your tires properly inflated can increase your fuel efficiency by three percent; and ensuring that your car is properly maintained can increase it by four percent. Remove any extra weight from the car.`,
    },
    {
      key: 25,
      category: `TRANSPORT`,
      title: `Combine errands/tasks`,
      content: `When doing errands, try to combine them to reduce your driving.`,
    },
    {
      key: 26,
      category: `TRANSPORT`,
      title: `Avoid traffic`,
      content: `Use traffic apps like Waze to help avoid getting stuck in traffic jams.`,
    },
    {
      key: 27,
      category: `TRANSPORT`,
      title: `Cruise control`,
      content: `On longer trips, turn on the cruise control, which can save gas.`,
    },
    {
      key: 28,
      category: `TRANSPORT`,
      title: `Reduce AC`,
      content: `Use less air conditioning while you drive, even when the weather is hot.`,
    },
    {
      key: 29,
      category: `TRANSPORT`,
      title: `Hybrid or electric vehicle.`,
      content: `If you're shopping for a new car, consider purchasing a hybrid or electric vehicle. But do factor in the greenhouse gas emissions from the production of the car as well as its operation. Some electric vehicles are initially responsible for more emissions than internal combustion engine vehicles because of manufacturing impacts; but they make up for it after three years.`,
    },
    {
      key: 30,
      category: `AIR TRAVEL`,
      title: `Fly nonstop`,
      content: `Fly nonstop since landings and takeoffs use more fuel and produce more emissions.`,
    },
    {
      key: 31,
      category: `AIR TRAVEL`,
      title: `Go economy class.`,
      content: `Business class is responsible for almost three times as many emissions as economy because in economy, the flight's carbon emissions are shared among more passengers; first class can result in nine times more carbon emissions than economy.`,
    },
    {
      key: 32,
      category: `AIR TRAVEL`,
      title: ` Avoid flying if possible;`,
      content: `If you fly for work or pleasure, air travel is probably responsible for the largest part of your carbon footprint. Avoid flying if possible; on shorter trips, driving may emit fewer greenhouse gases.`,
    },
  ];
  res.status(200).json(data);
}
